<?php
// 自動生成: scripts/build-wp-theme.mjs — 固定ページ階層とテンプレートの対応表
return array(
	'about' => array( 'title' => '企業情報', 'template' => 'templates/page-about.php' ),
	'about/history' => array( 'title' => '沿革', 'template' => 'templates/page-about-history.php' ),
	'about/message' => array( 'title' => 'トップメッセージ', 'template' => 'templates/page-about-message.php' ),
	'about/organization' => array( 'title' => 'グループ・組織図', 'template' => 'templates/page-about-organization.php' ),
	'about/outline' => array( 'title' => '会社概要', 'template' => 'templates/page-about-outline.php' ),
	'about/safety-health' => array( 'title' => '健康経営', 'template' => 'templates/page-about-safety-health.php' ),
	'about/standard' => array( 'title' => '行動基準', 'template' => 'templates/page-about-standard.php' ),
	'about/vision' => array( 'title' => '企業理念・ビジョン', 'template' => 'templates/page-about-vision.php' ),
	'business' => array( 'title' => '事業紹介', 'template' => 'templates/page-business.php' ),
	'business/ai-data-center' => array( 'title' => 'AIデータセンター事業', 'template' => 'templates/page-business-ai-data-center.php' ),
	'business/batteryenergystorage' => array( 'title' => '蓄電池事業（系統用蓄電池発電所開発）', 'template' => 'templates/page-business-batteryenergystorage.php' ),
	'business/biomasspower' => array( 'title' => 'バイオマス発電事業', 'template' => 'templates/page-business-biomasspower.php' ),
	'business/hopper' => array( 'title' => '走行式集塵ホッパー事業', 'template' => 'templates/page-business-hopper.php' ),
	'business/hydrogen-compressor' => array( 'title' => '水素コンプレッサー事業', 'template' => 'templates/page-business-hydrogen-compressor.php' ),
	'business/hydrogen-mobility' => array( 'title' => '水素モビリティ事業', 'template' => 'templates/page-business-hydrogen-mobility.php' ),
	'business/windpower' => array( 'title' => '風力発電事業', 'template' => 'templates/page-business-windpower.php' ),
	'contact' => array( 'title' => 'お問い合わせ', 'template' => 'templates/page-contact.php' ),
	'privacy' => array( 'title' => 'プライバシーポリシー', 'template' => 'templates/page-privacy.php' ),
	'products' => array( 'title' => '製品情報', 'template' => 'templates/page-products.php' ),
	'products/bms' => array( 'title' => 'BMS製品', 'template' => 'templates/page-products-bms.php' ),
	'products/bms/n-bams-10ht' => array( 'title' => 'N-BAMS-10HT', 'template' => 'templates/page-products-bms-n-bams-10ht.php' ),
	'products/bms/n-bcmu-w' => array( 'title' => 'N-BCMU-W', 'template' => 'templates/page-products-bms-n-bcmu-w.php' ),
	'products/bms/n-bmu-l37104-bd' => array( 'title' => 'N-BMU-L37104-BD', 'template' => 'templates/page-products-bms-n-bmu-l37104-bd.php' ),
	'products/ems' => array( 'title' => 'EMS製品', 'template' => 'templates/page-products-ems.php' ),
	'products/ems/n-bk-1000' => array( 'title' => 'N-BK-1000', 'template' => 'templates/page-products-ems-n-bk-1000.php' ),
	'products/ems/n-bk-2000' => array( 'title' => 'N-BK-2000', 'template' => 'templates/page-products-ems-n-bk-2000.php' ),
	'products/ems/n-bk-3000' => array( 'title' => 'N-BK-3000', 'template' => 'templates/page-products-ems-n-bk-3000.php' ),
	'products/pcs' => array( 'title' => 'PCS製品', 'template' => 'templates/page-products-pcs.php' ),
	'products/pcs/n-pcs-9567mv-5000' => array( 'title' => 'N-PCS-9567MV-5000', 'template' => 'templates/page-products-pcs-n-pcs-9567mv-5000.php' ),
	'products/pcs/n-pcs-9567tu-2500' => array( 'title' => 'N-PCS-9567TU-2500', 'template' => 'templates/page-products-pcs-n-pcs-9567tu-2500.php' ),
	'products/pcs/n-pcs-9726gmc' => array( 'title' => 'N-PCS-9726GMC', 'template' => 'templates/page-products-pcs-n-pcs-9726gmc.php' ),
	'products/pcs/n-pws1-1375ktl-h-jp-6m1-o' => array( 'title' => 'N-PWS1-1375KTL-H-JP-6M1-O', 'template' => 'templates/page-products-pcs-n-pws1-1375ktl-h-jp-6m1-o.php' ),
	'products/pcs/n-pws1-49-9m-jp-r' => array( 'title' => 'N-PWS1-49.9M-JP-R', 'template' => 'templates/page-products-pcs-n-pws1-49-9m-jp-r.php' ),
	'products/pcs/n-pwx1-1250ktl-h-ex' => array( 'title' => 'N-PWX1-1250KTL-H-EX', 'template' => 'templates/page-products-pcs-n-pwx1-1250ktl-h-ex.php' ),
	'recruit' => array( 'title' => '採用情報', 'template' => 'templates/page-recruit.php' ),
	'recruit/apply' => array( 'title' => '応募フォーム', 'template' => 'templates/page-recruit-apply.php' ),
	'recruit/electrical-engineer' => array( 'title' => '電気設備エンジニア｜募集要項', 'template' => 'templates/page-recruit-electrical-engineer.php' ),
	'recruit/hr-general-affairs' => array( 'title' => '人事・総務｜募集要項', 'template' => 'templates/page-recruit-hr-general-affairs.php' ),
	'recruit/sales' => array( 'title' => '営業募集｜募集要項', 'template' => 'templates/page-recruit-sales.php' ),
	'sustainability' => array( 'title' => 'サステナビリティ', 'template' => 'templates/page-sustainability.php' ),
	'sustainability/carbon-neutrality' => array( 'title' => 'カーボンニュートラル', 'template' => 'templates/page-sustainability-carbon-neutrality.php' ),
	'sustainability/community-relations' => array( 'title' => '地域共生', 'template' => 'templates/page-sustainability-community-relations.php' ),
	'sustainability/environment' => array( 'title' => '環境保全', 'template' => 'templates/page-sustainability-environment.php' ),
);
