<?php
// 自動生成: scripts/build-wp-theme.mjs — 固定ページ階層とテンプレートの対応表
return array(
	'about' => array( 'title' => '企業情報', 'template' => 'templates/page-about.php' ),
	'about/history' => array( 'title' => '沿革', 'template' => 'templates/page-about-history.php' ),
	'about/message' => array( 'title' => 'トップメッセージ', 'template' => 'templates/page-about-message.php' ),
	'about/organization' => array( 'title' => 'グループ・組織図', 'template' => 'templates/page-about-organization.php' ),
	'about/outline' => array( 'title' => '会社概要', 'template' => 'templates/page-about-outline.php' ),
	'about/safety-health' => array( 'title' => '健康経営', 'template' => 'templates/page-about-safety-health.php' ),
	'about/standard' => array( 'title' => '行動基準', 'template' => 'templates/page-about-standard.php' ),
	'about/vision' => array( 'title' => '企業理念・ビジョン', 'template' => 'templates/page-about-vision.php' ),
	'business' => array( 'title' => '事業紹介', 'template' => 'templates/page-business.php' ),
	'business/ai-data-center' => array( 'title' => 'AIデータセンター事業', 'template' => 'templates/page-business-ai-data-center.php' ),
	'business/batteryenergystorage' => array( 'title' => '蓄電池事業', 'template' => 'templates/page-business-batteryenergystorage.php' ),
	'business/biomasspower' => array( 'title' => 'バイオマス発電事業', 'template' => 'templates/page-business-biomasspower.php' ),
	'business/hopper' => array( 'title' => '走行式集塵ホッパー事業', 'template' => 'templates/page-business-hopper.php' ),
	'business/hydrogen-mobility' => array( 'title' => '水素モビリティ事業', 'template' => 'templates/page-business-hydrogen-mobility.php' ),
	'business/windpower' => array( 'title' => '風力発電事業', 'template' => 'templates/page-business-windpower.php' ),
	'contact' => array( 'title' => 'お問い合わせ', 'template' => 'templates/page-contact.php' ),
	'privacy' => array( 'title' => 'プライバシーポリシー', 'template' => 'templates/page-privacy.php' ),
	'recruit' => array( 'title' => '採用情報', 'template' => 'templates/page-recruit.php' ),
	'recruit/apply' => array( 'title' => '応募フォーム', 'template' => 'templates/page-recruit-apply.php' ),
	'recruit/electrical-engineer' => array( 'title' => '電気設備エンジニア｜募集要項', 'template' => 'templates/page-recruit-electrical-engineer.php' ),
	'recruit/hr-general-affairs' => array( 'title' => '人事・総務｜募集要項', 'template' => 'templates/page-recruit-hr-general-affairs.php' ),
	'recruit/sales' => array( 'title' => '営業募集｜募集要項', 'template' => 'templates/page-recruit-sales.php' ),
	'sustainability' => array( 'title' => 'サステナビリティ', 'template' => 'templates/page-sustainability.php' ),
	'sustainability/carbon-neutrality' => array( 'title' => 'カーボンニュートラル', 'template' => 'templates/page-sustainability-carbon-neutrality.php' ),
	'sustainability/community-relations' => array( 'title' => '地域共生', 'template' => 'templates/page-sustainability-community-relations.php' ),
	'sustainability/environment' => array( 'title' => '環境保全', 'template' => 'templates/page-sustainability-environment.php' ),
);
